stages:
  preprocess:
    cmd: ^
  train:
    cmd: python src/train.py
    deps:
    - processed/cleaned.csv
    - src/train.py
    params:
    - train.data
    - train.max_depth
    - train.model
    - train.n_estimators
    - train.random_state
    outs:
    - models/random_forest.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models/random_forest.pkl
    - src/evaluate.py
    outs:
    - reports/metrics.json
